### ISSUE TITLE
style: feedback on apollo

### ISSUE THREAD

**Issue by jcstein** [cmwaters/apollo#1]
i noticed one button doesn't have an associated URI: `bridge-p2p`

since the only endpoints available in a web browser are `faucet-api` and `comet-rpc`, do you think it would be useful to turn the other links into a "copied to clipboard" or show the URIs instead of having links? alternatively, show link and URI

looking good!

<img width="1728" alt="Screenshot 2024-03-22 at 1 07 46 PM" src="https://github.com/cmwaters/apollo/assets/46639943/937a3c43-ac1c-469f-a089-50b93b8a8ff1">

**Comment by cmwaters** [comment]
Yeah, good point. Either I can write something that understands whether a string is a URI or I can simply copy to clipboard. It would probably be nice to add an icon as well

**Comment by cmwaters** [comment]
In [embed statically served directories and display errors as popups](https://github.com/cmwaters/apollo/commit/a812123bdb26b26159275b12dfcb661442758631), I switched to copying the endpoint to the clipboard. I also created a popup to let users know. 

Thanks for the feedback!

**Comment by jcstein** [comment]
you're welcome! you beat me to it 😅
